/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.18 public/models/env2.glb -o src/components/Env2.jsx -r public 
Author: Janna Johns (https://sketchfab.com/jannajohns)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/wk2-env-blockout-janna-johns-673de5b07d02499e99b4de497258e6fc
Title: Wk2 Env Blockout  Janna Johns
*/

import React, { useEffect, useRef } from "react";
import { useGLTF } from "@react-three/drei";
import { RigidBody } from "@react-three/rapier";

export default function EnvTwo(props) {
    const { nodes, materials, scene } = useGLTF("/models/env2.glb");
    useEffect(() => {
        scene.traverse((child) => {
            if (child.isMesh) {
                child.castShadow = true;
                child.receiveShadow = true;
            }
        });
    });
    return (
        <RigidBody colliders="trimesh" type="fixed" name="hexagon" cdd>
            <group
                position={[0, 11.5, 125]}
                rotation={[1.554, -0.008, -2.941]}
                scale={[0.008, 0.008, 0.008]}
            >
                <group rotation={[Math.PI / 2, 0, 0]}>
                    <mesh
                        geometry={nodes.geo_cube1_lambert1_0.geometry}
                        material={materials.lambert1}
                        position={[12.231, 656.311, -34.536]}
                        rotation={[0.014, 0.006, 0.004]}
                        scale={[2.224, 1, 1]}
                    />
                    <mesh
                        geometry={nodes.geo_cube2_lambert1_0.geometry}
                        material={materials.lambert1}
                        position={[-18.454, 135.271, -1308.384]}
                        rotation={[1.518, 0.003, -0.002]}
                        scale={3.294}
                    />
                    <mesh
                        geometry={nodes.geo_cube3_lambert1_0.geometry}
                        material={materials.lambert1}
                        position={[-2940.609, 623.118, -48.376]}
                    />
                    <mesh
                        geometry={nodes.geo_cube4_lambert1_0.geometry}
                        material={materials.lambert1}
                        position={[2984.333, 622.569, -40.651]}
                    />
                    <mesh
                        geometry={nodes.geo_cylinder1_blinn5_0.geometry}
                        material={materials.blinn5}
                        position={[-278.11, 779.618, -1066.699]}
                    />
                    <mesh
                        geometry={nodes.geo_cylinder3_blinn5_0.geometry}
                        material={materials.blinn5}
                        position={[55.068, 772.778, -1069.279]}
                    />
                    <mesh
                        geometry={nodes.geo_cylinder4_blinn5_0.geometry}
                        material={materials.blinn5}
                        position={[357.378, 708.61, -1026.687]}
                    />
                    <mesh
                        geometry={nodes.geo_prism1_blinn5_0.geometry}
                        material={materials.blinn5}
                        position={[10.642, -346.971, -93.951]}
                        rotation={[-1.579, 0.476, -3.131]}
                        scale={0.914}
                    />
                    <mesh
                        geometry={nodes.geo_cylinder5_blinn5_0.geometry}
                        material={materials.blinn5}
                        position={[-550.42, 746.276, -1052.916]}
                    />
                    <mesh
                        geometry={nodes.geo_cylinder6_blinn5_0.geometry}
                        material={materials.blinn5}
                        position={[-821.664, 784.179, -1063.611]}
                    />
                    <mesh
                        geometry={nodes.geo_cylinder7_blinn5_0.geometry}
                        material={materials.blinn5}
                        position={[665.527, 770.57, -1049.541]}
                    />
                    <group position={[-177.686, 250.309, -8206.783]}>
                        <mesh
                            geometry={nodes.fountcube10_lambert1_0.geometry}
                            material={materials.lambert1}
                        />
                        <mesh
                            geometry={nodes.pCube16_lambert1_0.geometry}
                            material={materials.lambert1}
                            position={[-408.144, 2.352, -497.95]}
                            rotation={[-Math.PI, 1.539, -Math.PI]}
                        />
                    </group>
                    <mesh
                        geometry={nodes.fountcube1_lambert1_0.geometry}
                        material={materials.lambert1}
                        position={[-94.805, 1346.307, -1267.53]}
                        rotation={[-Math.PI / 2, 1.567, Math.PI / 2]}
                    />
                    <mesh
                        geometry={nodes.fountcube2_lambert1_0.geometry}
                        material={materials.lambert1}
                        position={[-110.884, 1340.076, -4657.53]}
                        rotation={[-Math.PI / 2, 1.567, 1.551]}
                    />
                    <mesh
                        geometry={nodes.fountcube3_lambert1_0.geometry}
                        material={materials.lambert1}
                        position={[-2664.748, 1311.732, -6017.202]}
                        rotation={[0.011, 0.868, -0.009]}
                        scale={[0.66, 0.738, 0.738]}
                    />
                    <mesh
                        geometry={nodes.fountcube4_lambert1_0.geometry}
                        material={materials.lambert1}
                        position={[-268.352, 1352.37, -12525.365]}
                        rotation={[-Math.PI / 2, 1.567, Math.PI / 2]}
                        scale={0.902}
                    />
                    <mesh
                        geometry={nodes.fountcube5_lambert1_0.geometry}
                        material={materials.lambert1}
                        position={[-3900.286, 1342.208, -8427.038]}
                        rotation={[0.018, 0.081, -0.001]}
                        scale={0.795}
                    />
                    <mesh
                        geometry={nodes.fountcube6_lambert1_0.geometry}
                        material={materials.lambert1}
                        position={[2540.979, 1296.935, -6206.999]}
                        rotation={[-0.001, -0.769, -0.001]}
                        scale={0.738}
                    />
                    <mesh
                        geometry={nodes.fountcube7_lambert1_0.geometry}
                        material={materials.lambert1}
                        position={[2601.013, 1313.286, -11477.357]}
                        rotation={[0.005, 0.776, -0.002]}
                        scale={0.739}
                    />
                    <mesh
                        geometry={nodes.fountcube8_lambert1_0.geometry}
                        material={materials.lambert1}
                        position={[3582.208, 1342.89, -8912.506]}
                        rotation={[0.005, 0.025, 0.001]}
                        scale={0.78}
                    />
                    <mesh
                        geometry={nodes.fountcube9_lambert1_0.geometry}
                        material={materials.lambert1}
                        position={[-3005.543, 1341.324, -11183.061]}
                        rotation={[-0.002, -0.667, 0.005]}
                        scale={0.794}
                    />
                    <mesh
                        geometry={nodes.fountcube11_lambert1_0.geometry}
                        material={materials.lambert1}
                        position={[-154.645, 250.522, -9200.88]}
                        rotation={[-0.001, 0, 0]}
                    />
                    <mesh
                        geometry={nodes.fountcube12_blinn3_0.geometry}
                        material={materials.blinn3}
                        position={[-351.895, 1388.673, -9968.631]}
                        scale={[0.68, 3.959, 0.818]}
                    />
                    <mesh
                        geometry={nodes.fountcube13_lambert1_0.geometry}
                        material={materials.lambert1}
                        position={[192.789, 250.414, -8718.315]}
                        rotation={[-Math.PI, 1.539, -Math.PI]}
                    />
                    <mesh
                        geometry={nodes.fountcube14_lambert1_0.geometry}
                        material={materials.lambert1}
                        position={[-154.645, 976.062, -10207.704]}
                        rotation={[-0.045, 0, 0]}
                        scale={[0.813, 0.435, 0.813]}
                    />
                    <mesh
                        geometry={nodes.fountcirc1_lambert1_0.geometry}
                        material={materials.lambert1}
                        position={[-112.933, 1354.472, -8945.497]}
                        rotation={[0, -0.053, -Math.PI]}
                        scale={[-1.253, 0.194, 1.253]}
                    />
                    <mesh
                        geometry={nodes.fountcirc3_lambert1_0.geometry}
                        material={materials.lambert1}
                        position={[-210.804, 1281.773, -8722.425]}
                        rotation={[0, -0.053, -Math.PI]}
                        scale={[-0.557, 0.086, 0.557]}
                    />
                    <mesh
                        geometry={nodes.fountcylinder1_lambert1_0.geometry}
                        material={materials.lambert1}
                        position={[-219.382, 1262.351, -8698.896]}
                        rotation={[-Math.PI, 0, 0]}
                        scale={[-2064.02, 2064.02, 2064.02]}
                    />
                    <mesh
                        geometry={nodes.fountcube15_lambert1_0.geometry}
                        material={materials.lambert1}
                        position={[-1677.22, 929.888, -8673.425]}
                        rotation={[-1.978, 1.506, 1.999]}
                        scale={[0.813, 0.435, 0.813]}
                    />
                    <mesh
                        geometry={nodes.fountcube16_lambert1_0.geometry}
                        material={materials.lambert1}
                        position={[-182.973, 929.888, -7081.042]}
                        rotation={[-3.074, 0.007, 3.118]}
                        scale={[0.813, 0.435, 0.813]}
                    />
                    <mesh
                        geometry={nodes.fountcube17_lambert1_0.geometry}
                        material={materials.lambert1}
                        position={[1237.123, 960.922, -8748.506]}
                        rotation={[-1.375, -1.512, -1.362]}
                        scale={[0.813, 0.435, 0.813]}
                    />
                    <mesh
                        geometry={nodes.fountcirc4_lambert1_0.geometry}
                        material={materials.lambert1}
                        position={[-230.875, 1277.3, -8705.064]}
                        rotation={[0, -0.053, -Math.PI]}
                        scale={[-0.485, 0.083, 0.512]}
                    />
                    <mesh
                        geometry={nodes.fountcirc5_lambert1_0.geometry}
                        material={materials.lambert1}
                        position={[-197.25, 1277.714, -8714.961]}
                        rotation={[0, -0.053, -Math.PI]}
                        scale={[-0.579, 0.09, 0.579]}
                    />
                    <mesh
                        geometry={nodes.fountcirc6_lambert1_0.geometry}
                        material={materials.lambert1}
                        position={[-165.36, 1260.584, -8661.951]}
                        rotation={[0, -0.067, -Math.PI]}
                        scale={[-0.444, 0.075, 0.464]}
                    />
                    <mesh
                        geometry={nodes.fountcube18_lambert1_0.geometry}
                        material={materials.lambert1}
                        position={[-5531.057, 1356.564, -13090.128]}
                        rotation={[-0.002, -0.667, 0.005]}
                        scale={0.794}
                    />
                    <mesh
                        geometry={nodes.fountcube19_lambert1_0.geometry}
                        material={materials.lambert1}
                        position={[-7093.925, 1341.127, -8189.697]}
                        rotation={[0.013, 0.081, -0.001]}
                        scale={0.795}
                    />
                    <mesh
                        geometry={nodes.fountcube23_lambert1_0.geometry}
                        material={materials.lambert1}
                        position={[6912.405, 1350.714, -9023.673]}
                        rotation={[0.005, 0.025, 0.001]}
                        scale={0.78}
                    />
                    <mesh
                        geometry={nodes.fountcube24_lambert1_0.geometry}
                        material={materials.lambert1}
                        position={[4450.444, 1291.271, -4361.737]}
                        rotation={[-0.001, -0.769, 0.005]}
                        scale={0.738}
                    />
                    <mesh
                        geometry={nodes.fountcube25_lambert1_0.geometry}
                        material={materials.lambert1}
                        position={[-4707.519, 1332.651, -3594.452]}
                        rotation={[0.011, 0.868, -0.009]}
                        scale={0.738}
                    />
                    <mesh
                        geometry={nodes.fountaincube26_lambert1_0.geometry}
                        material={materials.lambert1}
                        position={[8946.118, 1328.949, -9746.195]}
                        scale={[0.888, 0.281, 2.875]}
                    />
                    <mesh
                        geometry={nodes.fountaincube27_lambert1_0.geometry}
                        material={materials.lambert1}
                        position={[-9591.229, 1328.949, -9150.9]}
                        scale={[0.888, 0.281, 4.422]}
                    />
                    <mesh
                        geometry={nodes.fountcube26_lambert1_0.geometry}
                        material={materials.lambert1}
                        position={[-7842.838, 1341.127, -8114.851]}
                        rotation={[0.013, 0.081, -0.001]}
                        scale={0.795}
                    />
                    <mesh
                        geometry={nodes.fountcube27_lambert1_0.geometry}
                        material={materials.lambert1}
                        position={[-268.352, 1352.37, -16249.534]}
                        rotation={[-Math.PI / 2, 1.567, Math.PI / 2]}
                        scale={0.902}
                    />
                    <mesh
                        geometry={nodes.fountcube28_lambert1_0.geometry}
                        material={materials.lambert1}
                        position={[-268.352, 1352.37, -17455.918]}
                        rotation={[-Math.PI / 2, 1.567, Math.PI / 2]}
                        scale={0.902}
                    />
                    <mesh
                        geometry={nodes.fountcube29_lambert1_0.geometry}
                        material={materials.lambert1}
                        position={[-6965.522, 1356.564, -14214.146]}
                        rotation={[-0.002, -0.667, 0.005]}
                        scale={0.794}
                    />
                    <mesh
                        geometry={nodes.fountaincube28_lambert1_0.geometry}
                        material={materials.lambert1}
                        position={[8946.118, 1328.949, -4699.257]}
                        scale={[0.888, 0.281, 2.875]}
                    />
                    <mesh
                        geometry={nodes.fountaincube29_lambert1_0.geometry}
                        material={materials.lambert1}
                        position={[8946.118, 1328.949, -14809.341]}
                        scale={[0.888, 0.281, 2.875]}
                    />
                    <mesh
                        geometry={nodes.fountcube30_lambert1_0.geometry}
                        material={materials.lambert1}
                        position={[-268.352, 1352.37, -20476.916]}
                        rotation={[-Math.PI / 2, 1.567, Math.PI / 2]}
                        scale={0.902}
                    />
                    <mesh
                        geometry={nodes.tree_cylinder1_lambert1_0.geometry}
                        material={materials.lambert1}
                        position={[-1081.748, 827.506, -13718.298]}
                        rotation={[0, 0, -0.047]}
                        scale={[1, 2.969, 1]}
                    />
                    <mesh
                        geometry={nodes.tree_cylinder2_lambert1_0.geometry}
                        material={materials.lambert1}
                        position={[-1081.748, 827.506, -14902.219]}
                        rotation={[0, 0, -0.047]}
                        scale={[1, 2.969, 1]}
                    />
                    <mesh
                        geometry={nodes.tree_cylinder3_lambert1_0.geometry}
                        material={materials.lambert1}
                        position={[-1081.748, 827.506, -15397.218]}
                        rotation={[0, 0, -0.047]}
                        scale={[1, 2.969, 1]}
                    />
                    <mesh
                        geometry={nodes.tree_cylinder4_lambert1_0.geometry}
                        material={materials.lambert1}
                        position={[-1081.748, 827.506, -15937.395]}
                        rotation={[0, 0, -0.047]}
                        scale={[1, 2.969, 1]}
                    />
                    <mesh
                        geometry={nodes.tree_cylinder5_lambert1_0.geometry}
                        material={materials.lambert1}
                        position={[-1081.748, 827.506, -16481.322]}
                        rotation={[0, 0, -0.047]}
                        scale={[1, 2.969, 1]}
                    />
                    <mesh
                        geometry={nodes.tree_cylinder6_lambert1_0.geometry}
                        material={materials.lambert1}
                        position={[-1081.748, 827.506, -17003]}
                        rotation={[0, 0, -0.047]}
                        scale={[1, 2.969, 1]}
                    />
                    <mesh
                        geometry={nodes.tree_cylinder7_lambert1_0.geometry}
                        material={materials.lambert1}
                        position={[-1081.748, 827.506, -17731.053]}
                        rotation={[0, 0, -0.047]}
                        scale={[1, 2.969, 1]}
                    />
                    <mesh
                        geometry={nodes.tree_cylinder8_lambert1_0.geometry}
                        material={materials.lambert1}
                        position={[543.326, 827.506, -14902.219]}
                        rotation={[0, 0, -0.047]}
                        scale={[1, 2.969, 1]}
                    />
                    <mesh
                        geometry={nodes.tree_cylinder9_lambert1_0.geometry}
                        material={materials.lambert1}
                        position={[543.326, 827.506, -15393.825]}
                        rotation={[0, 0, -0.047]}
                        scale={[1, 2.969, 1]}
                    />
                    <mesh
                        geometry={nodes.tree_cylinder10_lambert1_0.geometry}
                        material={materials.lambert1}
                        position={[543.326, 827.506, -15949.997]}
                        rotation={[0, 0, -0.047]}
                        scale={[1, 2.969, 1]}
                    />
                    <mesh
                        geometry={nodes.tree_cylinder11_lambert1_0.geometry}
                        material={materials.lambert1}
                        position={[543.326, 827.506, -16416.113]}
                        rotation={[0, 0, -0.047]}
                        scale={[1, 2.969, 1]}
                    />
                    <mesh
                        geometry={nodes.tree_cylinder12_lambert1_0.geometry}
                        material={materials.lambert1}
                        position={[543.326, 827.506, -17084.695]}
                        rotation={[0, 0, -0.047]}
                        scale={[1, 2.969, 1]}
                    />
                    <mesh
                        geometry={nodes.tree_cylinder13_lambert1_0.geometry}
                        material={materials.lambert1}
                        position={[543.326, 827.506, -17707.969]}
                        rotation={[0, 0, -0.047]}
                        scale={[1, 2.969, 1]}
                    />
                    <mesh
                        geometry={nodes.tree_cylinder14_lambert1_0.geometry}
                        material={materials.lambert1}
                        position={[589.855, 827.506, -13718.298]}
                        rotation={[0, 0, -0.047]}
                        scale={[1, 2.969, 1]}
                    />
                    <mesh
                        geometry={nodes.tree_cylinder15_lambert1_0.geometry}
                        material={materials.lambert1}
                        position={[1277.953, 827.506, -13563.821]}
                        rotation={[0, 0, -0.047]}
                        scale={[1, 2.969, 1]}
                    />
                    <mesh
                        geometry={nodes.tree_cylinder16_lambert1_0.geometry}
                        material={materials.lambert1}
                        position={[-1797.586, 827.506, -13563.821]}
                        rotation={[0, 0, -0.047]}
                        scale={[1, 2.969, 1]}
                    />
                    <mesh
                        geometry={nodes.tree_cylinder17_lambert1_0.geometry}
                        material={materials.lambert1}
                        position={[1831.338, 827.506, -13427.849]}
                        rotation={[0, 0, -0.047]}
                        scale={[1, 2.969, 1]}
                    />
                    <mesh
                        geometry={nodes.tree_cylinder18_lambert1_0.geometry}
                        material={materials.lambert1}
                        position={[-2458.096, 827.506, -13257.519]}
                        rotation={[0, 0, -0.047]}
                        scale={[1, 2.969, 1]}
                    />
                    <mesh
                        geometry={nodes.tree_cylinder19_lambert1_0.geometry}
                        material={materials.lambert1}
                        position={[2543.183, 827.506, -13044.831]}
                        rotation={[0, 0, -0.047]}
                        scale={[1, 2.969, 1]}
                    />
                    <mesh
                        geometry={nodes.tree_cylinder20_lambert1_0.geometry}
                        material={materials.lambert1}
                        position={[-3078.585, 827.506, -12885.544]}
                        rotation={[0, 0, -0.047]}
                        scale={[1, 2.969, 1]}
                    />
                    <mesh
                        geometry={nodes.tree_cylinder21_lambert1_0.geometry}
                        material={materials.lambert1}
                        position={[-4726.44, 827.506, -10891.173]}
                        rotation={[0, 0, -0.047]}
                        scale={[1, 2.969, 1]}
                    />
                    <mesh
                        geometry={nodes.tree_cylinder22_lambert1_0.geometry}
                        material={materials.lambert1}
                        position={[-4880.384, 827.506, -10267.061]}
                        rotation={[0, 0, -0.047]}
                        scale={[1, 2.969, 1]}
                    />
                    <mesh
                        geometry={nodes.tree_cyl_23_lambert1_0.geometry}
                        material={materials.lambert1}
                        position={[-4979.57, 827.506, -9605.341]}
                        rotation={[0, 0, -0.047]}
                        scale={[1, 2.969, 1]}
                    />
                    <mesh
                        geometry={nodes.tree_cyl_24_lambert1_0.geometry}
                        material={materials.lambert1}
                        position={[-4638.036, 827.506, -7166.998]}
                        rotation={[0, 0, -0.047]}
                        scale={[1, 2.969, 1]}
                    />
                    <mesh
                        geometry={nodes.tree_cyl_25_lambert1_0.geometry}
                        material={materials.lambert1}
                        position={[-4454.88, 827.506, -6702.98]}
                        rotation={[0, 0, -0.047]}
                        scale={[1, 2.969, 1]}
                    />
                    <mesh
                        geometry={nodes.tree_cyl_26_lambert1_0.geometry}
                        material={materials.lambert1}
                        position={[-4160.883, 827.506, -6233.433]}
                        rotation={[0, 0, -0.047]}
                        scale={[1, 2.969, 1]}
                    />
                    <mesh
                        geometry={nodes.tree_cyl_27_lambert1_0.geometry}
                        material={materials.lambert1}
                        position={[-2469.958, 827.506, -4673.436]}
                        rotation={[0, 0, -0.047]}
                        scale={[1, 2.969, 1]}
                    />
                    <mesh
                        geometry={nodes.pCylinder28_lambert1_0.geometry}
                        material={materials.lambert1}
                        position={[-1972.015, 827.506, -4456.833]}
                        rotation={[0, 0, -0.047]}
                        scale={[1, 2.969, 1]}
                    />
                    <mesh
                        geometry={nodes.pCylinder29_lambert1_0.geometry}
                        material={materials.lambert1}
                        position={[-1412.448, 827.506, -4237.041]}
                        rotation={[0, 0, -0.047]}
                        scale={[1, 2.969, 1]}
                    />
                    <mesh
                        geometry={nodes.pCylinder30_lambert1_0.geometry}
                        material={materials.lambert1}
                        position={[845.446, 827.506, -4161.596]}
                        rotation={[0, 0, -0.047]}
                        scale={[1, 2.969, 1]}
                    />
                    <mesh
                        geometry={nodes.pCylinder31_lambert1_0.geometry}
                        material={materials.lambert1}
                        position={[1325.858, 827.506, -4309.263]}
                        rotation={[0, 0, -0.047]}
                        scale={[1, 2.969, 1]}
                    />
                    <mesh
                        geometry={nodes.pCylinder32_lambert1_0.geometry}
                        material={materials.lambert1}
                        position={[1883.428, 827.506, -4509.361]}
                        rotation={[0, 0, -0.047]}
                        scale={[1, 2.969, 1]}
                    />
                    <mesh
                        geometry={nodes.pCylinder33_lambert1_0.geometry}
                        material={materials.lambert1}
                        position={[2397.441, 827.506, -4791.286]}
                        rotation={[0, 0, -0.047]}
                        scale={[1, 2.969, 1]}
                    />
                    <mesh
                        geometry={nodes.pCylinder34_lambert1_0.geometry}
                        material={materials.lambert1}
                        position={[4008.499, 827.506, -6380.39]}
                        rotation={[0, 0, -0.047]}
                        scale={[1, 2.969, 1]}
                    />
                    <mesh
                        geometry={nodes.pCylinder35_lambert1_0.geometry}
                        material={materials.lambert1}
                        position={[4259.717, 827.506, -6840.668]}
                        rotation={[0, 0, -0.047]}
                        scale={[1, 2.969, 1]}
                    />
                    <mesh
                        geometry={nodes.pCylinder36_lambert1_0.geometry}
                        material={materials.lambert1}
                        position={[4495.667, 827.506, -7358.097]}
                        rotation={[0, 0, -0.047]}
                        scale={[1, 2.969, 1]}
                    />
                    <mesh
                        geometry={nodes.pCylinder37_lambert1_0.geometry}
                        material={materials.lambert1}
                        position={[4635.451, 827.506, -7962.375]}
                        rotation={[0, 0, -0.047]}
                        scale={[1, 2.969, 1]}
                    />
                    <mesh
                        geometry={nodes.pCylinder38_lambert1_0.geometry}
                        material={materials.lambert1}
                        position={[4635.451, 827.506, -9824.329]}
                        rotation={[0, 0, -0.047]}
                        scale={[1, 2.969, 1]}
                    />
                    <mesh
                        geometry={nodes.pCylinder39_lambert1_0.geometry}
                        material={materials.lambert1}
                        position={[4482.778, 827.506, -10366.437]}
                        rotation={[0, 0, -0.047]}
                        scale={[1, 2.969, 1]}
                    />
                    <mesh
                        geometry={nodes.pCylinder40_lambert1_0.geometry}
                        material={materials.lambert1}
                        position={[4249.119, 827.506, -11008.068]}
                        rotation={[0, 0, -0.047]}
                        scale={[1, 2.969, 1]}
                    />
                    <mesh
                        geometry={nodes.pCylinder41_lambert1_0.geometry}
                        material={materials.lambert1}
                        position={[4057.74, 827.506, -11429.605]}
                        rotation={[0, 0, -0.047]}
                        scale={[1, 2.969, 1]}
                    />
                    <mesh
                        geometry={nodes.pSphere2_lambert1_0.geometry}
                        material={materials.lambert1}
                        position={[4031.51, 163.484, -11416.629]}
                        scale={[1.041, 0.79, 0.79]}
                    />
                    <mesh
                        geometry={nodes.pSphere17_lambert1_0.geometry}
                        material={materials.lambert1}
                        position={[-1097.24, 290.109, -13712.253]}
                        scale={[0.724, 0.945, 0.945]}
                    />
                    <mesh
                        geometry={nodes.pSphere21_lambert1_0.geometry}
                        material={materials.lambert1}
                        position={[-4735.555, 386.625, -10890.23]}
                        scale={[1.207, 0.818, 0.818]}
                    />
                    <mesh
                        geometry={nodes.pSphere33_lambert1_0.geometry}
                        material={materials.lambert1}
                        position={[530.245, 323.85, -16415.75]}
                        scale={[1.176, 1.239, 1.039]}
                    />
                    <mesh
                        geometry={nodes.pSphere34_lambert1_0.geometry}
                        material={materials.lambert1}
                        position={[529.217, 334.166, -17083.568]}
                        scale={[0.781, 1.065, 0.734]}
                    />
                    <mesh
                        geometry={nodes.pSphere35_lambert1_0.geometry}
                        material={materials.lambert1}
                        position={[511.284, 334.166, -17704.16]}
                        scale={[1.025, 0.79, 0.79]}
                    />
                    <mesh
                        geometry={nodes.pSphere36_lambert1_0.geometry}
                        material={materials.lambert1}
                        position={[-1133.285, 334.166, -17704.16]}
                        scale={[0.997, 0.79, 0.79]}
                    />
                    <mesh
                        geometry={nodes.pSphere37_lambert1_0.geometry}
                        material={materials.lambert1}
                        position={[-1085.542, 334.166, -17003.719]}
                        scale={[0.921, 1.066, 0.79]}
                    />
                    <mesh
                        geometry={nodes.pSphere42_lambert1_0.geometry}
                        material={materials.lambert1}
                        position={[-1085.542, 334.166, -16481.373]}
                        scale={[0.921, 1.066, 0.79]}
                    />
                    <mesh
                        geometry={nodes.pSphere43_lambert1_0.geometry}
                        material={materials.lambert1}
                        position={[-1133.285, 334.166, -15955.894]}
                        scale={[0.997, 0.79, 0.79]}
                    />
                    <mesh
                        geometry={nodes.pSphere44_lambert1_0.geometry}
                        material={materials.lambert1}
                        position={[-1085.542, 334.166, -15411.446]}
                        scale={[0.921, 1.066, 0.79]}
                    />
                    <mesh
                        geometry={nodes.pSphere45_lambert1_0.geometry}
                        material={materials.lambert1}
                        position={[-1124.803, 323.85, -14865.764]}
                        scale={[1.176, 1.239, 1.039]}
                    />
                    <mesh
                        geometry={nodes.pSphere46_lambert1_0.geometry}
                        material={materials.lambert1}
                        position={[426.683, 334.166, -15955.894]}
                        scale={[0.997, 0.79, 0.79]}
                    />
                    <mesh
                        geometry={nodes.pSphere47_lambert1_0.geometry}
                        material={materials.lambert1}
                        position={[530.245, 323.85, -15411.723]}
                        scale={[1.176, 1.239, 1.039]}
                    />
                    <mesh
                        geometry={nodes.pSphere48_lambert1_0.geometry}
                        material={materials.lambert1}
                        position={[511.284, 334.166, -14890.516]}
                        scale={[1.025, 0.79, 0.79]}
                    />
                    <mesh
                        geometry={nodes.pSphere49_lambert1_0.geometry}
                        material={materials.lambert1}
                        position={[-1772.477, 290.109, -13583.148]}
                        scale={[0.724, 0.945, 0.945]}
                    />
                    <mesh
                        geometry={nodes.pSphere50_lambert1_0.geometry}
                        material={materials.lambert1}
                        position={[-2508.524, 228.32, -13242.588]}
                        scale={[1.176, 1.239, 1.039]}
                    />
                    <mesh
                        geometry={nodes.pSphere51_lambert1_0.geometry}
                        material={materials.lambert1}
                        position={[-3146.259, 260.413, -12895.503]}
                        scale={[0.997, 0.79, 0.79]}
                    />
                    <mesh
                        geometry={nodes.pSphere52_lambert1_0.geometry}
                        material={materials.lambert1}
                        position={[570.722, 323.85, -13704.017]}
                        scale={[1.176, 1.239, 1.039]}
                    />
                    <mesh
                        geometry={nodes.pSphere53_lambert1_0.geometry}
                        material={materials.lambert1}
                        position={[1269.074, 334.166, -13591.04]}
                        scale={[1.025, 0.79, 0.79]}
                    />
                    <mesh
                        geometry={nodes.pSphere54_lambert1_0.geometry}
                        material={materials.lambert1}
                        position={[1825.148, 276.946, -13412.25]}
                        scale={[0.997, 0.79, 0.79]}
                    />
                    <mesh
                        geometry={nodes.pSphere55_lambert1_0.geometry}
                        material={materials.lambert1}
                        position={[2496.722, 304.695, -12970.206]}
                        scale={[1.263, 0.79, 0.912]}
                    />
                    <mesh
                        geometry={nodes.pSphere56_lambert1_0.geometry}
                        material={materials.lambert1}
                        position={[4225.07, 163.484, -11009.176]}
                        scale={[1.29, 0.98, 0.98]}
                    />
                    <mesh
                        geometry={nodes.pSphere57_lambert1_0.geometry}
                        material={materials.lambert1}
                        position={[4466.646, 304.695, -10369.007]}
                        scale={[1.025, 0.79, 0.79]}
                    />
                    <mesh
                        geometry={nodes.pSphere58_lambert1_0.geometry}
                        material={materials.lambert1}
                        position={[4567.333, 188.391, -9795.021]}
                        scale={[1.406, 1.084, 0.861]}
                    />
                    <mesh
                        geometry={nodes.pSphere59_lambert1_0.geometry}
                        material={materials.lambert1}
                        position={[-4844.264, 339.751, -10226.804]}
                        scale={[1.564, 1.06, 1.06]}
                    />
                    <mesh
                        geometry={nodes.pSphere60_lambert1_0.geometry}
                        material={materials.lambert1}
                        position={[-4950.437, 292.786, -9583.409]}
                        scale={[1.207, 0.818, 0.818]}
                    />
                    <mesh
                        geometry={nodes.pSphere61_lambert1_0.geometry}
                        material={materials.lambert1}
                        position={[-4612.654, 228.32, -7152.888]}
                        scale={[1.176, 1.239, 1.039]}
                    />
                    <mesh
                        geometry={nodes.pSphere62_lambert1_0.geometry}
                        material={materials.lambert1}
                        position={[-4526.487, 119.452, -6732.499]}
                        scale={[0.997, 0.79, 0.79]}
                    />
                    <mesh
                        geometry={nodes.pSphere63_lambert1_0.geometry}
                        material={materials.lambert1}
                        position={[-4224.761, 228.32, -6173.466]}
                        scale={[1.176, 1.239, 1.039]}
                    />
                    <mesh
                        geometry={nodes.pSphere64_lambert1_0.geometry}
                        material={materials.lambert1}
                        position={[4640.449, 163.484, -7987.862]}
                        scale={[1.29, 0.98, 0.98]}
                    />
                    <mesh
                        geometry={nodes.pSphere65_lambert1_0.geometry}
                        material={materials.lambert1}
                        position={[4473.678, 304.695, -7396.552]}
                        scale={[1.025, 0.79, 0.79]}
                    />
                    <mesh
                        geometry={nodes.pSphere66_lambert1_0.geometry}
                        material={materials.lambert1}
                        position={[4221.942, 144.648, -6821.954]}
                        scale={[1.041, 0.79, 0.79]}
                    />
                    <mesh
                        geometry={nodes.pSphere67_lambert1_0.geometry}
                        material={materials.lambert1}
                        position={[4035.265, 137.438, -6347.619]}
                        scale={[1.025, 0.79, 0.79]}
                    />
                    <mesh
                        geometry={nodes.pSphere68_lambert1_0.geometry}
                        material={materials.lambert1}
                        position={[-2454.821, 228.32, -4692.431]}
                        scale={[1.176, 1.239, 1.039]}
                    />
                    <mesh
                        geometry={nodes.pSphere69_lambert1_0.geometry}
                        material={materials.lambert1}
                        position={[-1459.616, 228.32, -4253.169]}
                        scale={[1.176, 1.239, 1.039]}
                    />
                    <mesh
                        geometry={nodes.pSphere70_lambert1_0.geometry}
                        material={materials.lambert1}
                        position={[-2026.558, 228.32, -4483.15]}
                        scale={[1.176, 1.239, 1.039]}
                    />
                    <mesh
                        geometry={nodes.pSphere71_lambert1_0.geometry}
                        material={materials.lambert1}
                        position={[2411.08, 137.438, -4739.442]}
                        scale={[1.025, 0.79, 0.79]}
                    />
                    <mesh
                        geometry={nodes.pSphere72_lambert1_0.geometry}
                        material={materials.lambert1}
                        position={[1850.934, 137.438, -4519.064]}
                        scale={[1.025, 0.79, 0.79]}
                    />
                    <mesh
                        geometry={nodes.pSphere73_lambert1_0.geometry}
                        material={materials.lambert1}
                        position={[799.171, 228.32, -4149.854]}
                        scale={[1.176, 1.239, 1.039]}
                    />
                    <mesh
                        geometry={nodes.pSphere74_lambert1_0.geometry}
                        material={materials.lambert1}
                        position={[1298.61, 228.32, -4330.343]}
                        scale={[1.176, 1.239, 1.039]}
                    />
                </group>
            </group>
        </RigidBody>
    );
}

useGLTF.preload("/models/env2.glb");
